### ISSUE TITLE
A DB Exec Failed!, Error: Table

### ISSUE THREAD

**Issue by tr0ut33** [Cacti/plugin_mactrack#146]
Cacti version = 1.2.14
Mactrack version = 4.4
SQL = 10.3.24-MariaDB

23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[881]:db_execute(), /lib/database.php[213]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[877]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_ips' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[875]:db_execute(), /lib/database.php[213]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_temp_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[864]:db_execute(), /lib/database.php[213]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_aggregated_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[863]:db_execute(), /lib/database.php[213]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_aggregated_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[858]:mactrack_process_mac_auth_report(), /plugins/mactrack/poller_mactrack.php[892]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.mac_track_temp_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[759]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.mac_track_ips' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[679]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.mac_track_temp_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[663]:db_execute(), /lib/database.php[213]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[627]:db_execute(), /lib/database.php[213]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_temp_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[619]:db_execute(), /lib/database.php[213]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_temp_ports' doesn't exist
23/Oct/2020 17:18:10 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[614]:db_execute_prepared())
23/Oct/2020 17:18:10 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_temp_ports' doesn't exist

**Comment by TheWitness** [comment]
Go into the mysql prompt and run the following.  After that, the problem should be solved:

```sql
CREATE TABLE `mac_track_temp_ports` (
  `site_id` int(10) unsigned NOT NULL DEFAULT 0,
  `device_id` int(10) unsigned NOT NULL DEFAULT 0,
  `hostname` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `device_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `vlan_id` varchar(5) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N/A',
  `vlan_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `mac_address` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `vendor_mac` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_address` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `dns_hostname` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `port_number` int(10) unsigned NOT NULL DEFAULT 0,
  `port_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `scan_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `authorized` tinyint(3) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`port_number`,`scan_date`,`mac_address`,`device_id`),
  KEY `site_id` (`site_id`),
  KEY `device_name` (`device_name`),
  KEY `ip_address` (`ip_address`),
  KEY `hostname` (`hostname`),
  KEY `vlan_name` (`vlan_name`),
  KEY `vlan_id` (`vlan_id`),
  KEY `device_id` (`device_id`),
  KEY `mac` (`mac_address`),
  KEY `updated` (`updated`),
  KEY `vendor_mac` (`vendor_mac`),
  KEY `authorized` (`authorized`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Database for Storing Temporary Results for Tracking Device MACS'
```

**Comment by tr0ut33** [comment]
Hi TheWitness,

Many thanks for the prompt reply.  

I have created the "mac_track_temp_ports" Table, but am still getting the following errors :

CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_ports' doesn't exist
CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_ips' doesn't exist
CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.mac_track_aggregated_ports' doesn't exist

Many thanks

**Comment by TheWitness** [comment]
What Cacti version are you working with?  You must be at 1.2.14+ to use the current development branch.  If you are not at that release, I suggest you do the following:

1) Uninstall MacTrack
2) Upgrade Cacti to 1.2.14
3) Re-install MacTrack

**Comment by TheWitness** [comment]
It looks like you are there already.  Uninstall and re-install and check the log for errors.
